<<<<<<< HEAD
# Site Settings
name: Project
title: Dimas | Project
description: A range of data science projects is available for exploration, showcasing skills in analyzing and visualizing data to uncover valuable insights and solve real-world problems. Each project reflects a commitment to applying data science techniques effectively and creatively. This portfolio is continuously updated with new projects, analyses, and visualizations to reflect an ongoing commitment to the field. Feel free to browse through the projects below to see how various challenges have been tackled and how contributions to understanding and improving business strategies and decision-making have been made..
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
 # - title: Feed
 #   url: /feed.xml
email: senddimasadit@gmail.com
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
#formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: dimasrepo
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
linkedin_username: dimas-a-11b184122/
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
# version: v3.1.2
=======
# Site Settings
name: Project
title: Dimas | Project
description: A range of data science projects is available for exploration, showcasing skills in analyzing and visualizing data to uncover valuable insights and solve real-world problems. Each project reflects a commitment to applying data science techniques effectively and creatively. This portfolio is continuously updated with new projects, analyses, and visualizations to reflect an ongoing commitment to the field. Feel free to browse through the projects below to see how various challenges have been tackled and how contributions to understanding and improving business strategies and decision-making have been made..
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
 # - title: Feed
 #   url: /feed.xml
email: senddimasadit@gmail.com
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
#formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: dimasrepo
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
linkedin_username: dimas-a-11b184122/
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
# version: v3.1.2
>>>>>>> 033733c423a5d21c4d58af8ed8bfd897a440038a
